### ISSUE TITLE
requirements

### ISSUE THREAD

**Issue by fpalombini** [ace-wg/ace-oscore-profile#18]
@jimsch In section 3.2, the following requirements are imposed:
*  The AS MAY assign an identifier to the client
*  The AS MUST assign an identifier to the RS
*  The client identifiers MUST be unique in the set of all clients on a
single RS
*  The RS identifiers MUST be unique in the set of all RS for any given
client.

If it is not required to assign an identifier for the client, how can it be
unique?
If there are multiple AS, each with a set of unique RS, are the AS servers
expected to coordinate in order to make the RS identifiers unique?

**Comment by fpalombini** [comment]
> If it is not required to assign an identifier for the client, how can it be
unique?

If I remember correctly, the MAY in "The AS MAY assign an identifier to the client" comes from the fact that the client can provide a client ID to the AS that it would like to use (in the "client_id" field of the request to the AS). Then the AS can either use that (if it does not collide with others), or change that to make it unique for the RS. We probably need more text about this (in particular on the requirements on the AS to send a new client ID if the one provided is not good), would that work?

> If there are multiple AS, each with a set of unique RS, are the AS servers
expected to coordinate in order to make the RS identifiers unique?

Do you mean: several RS contacted by one client, each RS having a different AS? Yes, I think that is missing. I will add a sentence about that.

**Comment by jimsch** [comment]
Ok - One of use is very confused at this point and that seems to be a problem.  

The client id is used by the server to identify the sender of the message.  For this reason the identifier needs to be unique on the server side and must exist - and empty identifier is an identifier and needs to be set as such.  As such, the same client ID can be assigned to a single client in when dealing with multiple contexts for different RSs as long as the client ID is unique for each RS.  

A client could want to request a specific server ID be assigned in a new context since it might want a unique (for it) server id be assigned to an RS.   In many cases a server ID is not ever put into a message as it is a response and thus the server's context can be inferred.  The exception to this being if an observe operation has been done.  Only in that case would the server send it's context as part of a message.

Ok - which of us is totally out to sea.

**Comment by fpalombini** [comment]
I'm trying to understand your issue still.

I agree with your latest text, although I thought we were discussing uniqueness of Client ID, not Server ID. So let's discuss both.

### Uniqueness of Client ID

Initial comment was:

> If it is not required to assign an identifier for the client, how can it be
> unique?

There are 2 cases: either the AS sets the Client ID of clients, or it does not. If it does, the AS is supposed to keep track of what IDs are available for the RS, so it is able to assign a unique one. If it does not, the RS sets the Client ID in the 2.01 Created response to the POST request, as section 4.2 specifies:

> Moreover, if the OSCORE_Security_Context in the token did not contain a 'clientId' parameter, the RS MUST generate an identifier, unique in the set of all its existing client identifiers, and send it in a 'clientId' parameter in the CBOR map as a CBOR bstr.

Note that if the AS assigns ID for some clients but not for others, this could be messed up, i.e. it might end up not keeping track and provide the client with an ID that the RS has already assigned to someone else. But this could be quickly solved, modifying the sentence above as follows:

> Moreover, if the OSCORE_Security_Context in the token did not contain a 'clientId' parameter, or the 'clientId' value collides with the value from another client, the RS MUST generate an identifier, unique in the set of all its existing client identifiers, and send it in a 'clientId' parameter in the CBOR map as a CBOR bstr.

Does this make sense? does it answer your comment about uniqueness of client ID?

### Uniqueness of Server ID

This comment to me refers to the Server ID not being unique on the client: 

> A client could want to request a specific server ID be assigned in a new context since it might want a unique (for it) server id be assigned to an RS. In many cases a server ID is not ever put into a message as it is a response and thus the server's context can be inferred. The exception to this being if an observe operation has been done. Only in that case would the server send its context as part of a message.

Are you saying it should not be necessary for the client that different RS are identified uniquely? Because most of the time, the client knows what is expecting. I can agree with that. Also, there is no exception in the case of Observe, the client has saved the observation and the token so it knows what context to use.

So yes, I agree that this action is needed in the text:
- remove requirement on Server ID being unique for its set of unique clients (that's true for Group OSCORE)

(if this uniqueness requirement is necessary, then a sentence about AS needing to coordinate is needed, although that seems like unnecessary and very heavy)

**Comment by fpalombini** [comment]
Concerning the "Uniqueness of Client ID" point, and the proposal to add the following sentence to the text:

> or the 'clientId' value collides with the value from another client 

The text is actually already there, in the next sentence:

>    The RS MAY
>    generate and send a 'ClientId' identifier even though the
>    OSCORE_Security_Context contained such a parameter, in order to
>    guarantee the uniqueness of the client identifier.
