### ISSUE TITLE
Unhappyness with where the nonces are put for derivation

### ISSUE THREAD

**Issue by jimsch** [ace-wg/ace-oscore-profile#23]
I am not happy with where the nonces are placed for doing key derivation.

1.  My code assume(d) that if you pass in a context field, then it is a context field and should be sent as part of a message.
2.  It killed an experiment that I was going to run because I was just not sure how to go about it.  I was going to run two different AS systems and I was going to use the context field to separate the two AS systems.  This would have solved my client id problem in this case as the client id spaces would be unique to each of the AS systems (unique context field).  However, this is now hard to run esp as it is no longer included in the key derivation process.  

I would have been happier if nonces were appended to the end of the salt field.

**Comment by LudwigSeitz** [comment]
I agree that putting the nonces in the salt field makes more sense than putting them in the id-context (or was it context-id?) field. Can we make that change or do we need to wait for the AD reviews?

**Comment by fpalombini** [comment]
Motivation for this was part of the decision made at IETF103 (see [minutes](https://datatracker.ietf.org/meeting/103/materials/minutes-103-ace-00) and [slides](https://datatracker.ietf.org/meeting/103/materials/slides-103-ace-oscore-profile-of-ace-02) where people supported "proposal 3")

But I see the point of this issue and will go ahead and make the change.

**Comment by fpalombini** [comment]
where would the id context be transported in case of update to access rights? (Right now we were only sending the client id, we might need to send both I think)

My proposal: "kid" = CBOR array [ clientId , ? ID Context ]

**Comment by kaduk** [comment]
> Motivation for this was part of the decision made at IETF103 (see [minutes](https://datatracker.ietf.org/meeting/103/materials/minutes-103-ace-00) and [slides](https://datatracker.ietf.org/meeting/103/materials/slides-103-ace-oscore-profile-of-ace-02) where people supported "proposal 3")
> 
> But I see the point of this issue and will go ahead and make the change.

Thanks (and for not waiting for the AD review).
