### ISSUE TITLE
Table 1

### ISSUE THREAD

**Issue by fpalombini** [ace-wg/ace-oscore-profile#36]
> Description: OSCORE Sender ID value of the client, OSCORE Recipient ID value of the server  

For Sender ID: do we want to add **CoAP** client/server? (and same for Recipient ID)

This is related to the discussion with @jimsch and @chrysn

**Comment by chrysn** [comment]
Suggestion: "OSCORE sender ID of the ACE client that requested the token, OSCORE recipient ID of the ACE RS"

"CoAP client/server" would not really help, as in future communication that's exactly what can switch.

(I tried to shorten the wording, but stopped when it occurred to me that the original RS could, during role-reversed communication, try to upgrade its own client credentials on the OSCORE context, and that's where terminology gets messy.)

**Comment by fpalombini** [comment]
Mmmmh yes that would be more precise in this document, but I was hoping to get a more general definition (not based on Ace roles) in case we would want to use this same structure (OSCORE_Security_Context) elsewhere, where Ace roles would not apply... to me it would be CoAP Client and Sender implying *at the time of sending/receiving*...

**Comment by chrysn** [comment]
One way to make it more generic would be to do a bit like in EDHOC and speak of parties A and B, and say in the application to ACE-OSCORE that party A is the client and party B is the server. (But given the structure is not defined for this more general purpose here, that'd be a hard sell.)

**Comment by fpalombini** [comment]
Right... I guess we could keep "client" and "server" terminology here (which is willingly ambiguous) in the IANA registration, and in the text where these fields are used add some clarification that those terms in this document refer to the Ace client and server to the Ace RS server.
