### ISSUE TITLE
input salt

### ISSUE THREAD

**Issue by fpalombini** [ace-wg/ace-oscore-profile#37]
salt in OSCORE Security Context is defined as:

> Description: OSCORE Master Salt value

But it is used as one of the inputs to OSCORE Master Salt... should we rephrase this definition?

(Also requires editorial modifications to make it correct in the rest of the text).

**Comment by kaduk** [comment]
Rephrasing the definition seems like the right thing to do.  There's probably some flexibility about whether we literally say "an input to the OSCORE Master Salt", "unique per-token salt", or something else.

**Comment by fpalombini** [comment]
I like "an input to the OSCORE Master Salt". Thanks!
