### ISSUE TITLE
Figure 7 caption + clarification text

### ISSUE THREAD

**Issue by fpalombini** [ace-wg/ace-oscore-profile#39]
Linda Dumbar for Ops-Dir review:

It seems to me there are 4 columns but  I can't understand the meaning of the values under 1st, 2nd, and 3rd columns. 

I think clarifying in the caption of figure 7 (and possibly the text above) that this is the output of CBOR encoded bytes, formatted for easiness of readability, might help the reader.

**Comment by kaduk** [comment]
It seems like it can't hurt, yes.
