### ISSUE TITLE
Precision on "The access token MUST be encrypted"

### ISSUE THREAD

**Issue by chrysn** [ace-wg/ace-oscore-profile#40]
The encryption requirement is good for the case where the cnf is transported inside the token, but needless otherwise.

Suggestion:

>    The same parameters MUST be included as part of the access token.
>   This profile RECOMMENDS the use of CBOR web token (CWT) as specified
>   in [RFC8392].  If the token is a CWT, the same
>   OSCORE_Security_Context structure defined above MUST be placed in the
>   'osc' field of the 'cnf' claim of this token.  The access token MUST
>   be encrypted
>   **if it contains key material (as is the case with CWT)**,
>   since it will be transferred from the client to the RS
>   over an unprotected channel.

Emphasis indicates addition. The requirement is repeated in section 4.1.

A use case where this came up is bootstrapping:

Suppose I'm commissioning (flashing) a lot of devices, and all I get them is a way to access the AS. Then I could of course set them up with an OSCORE context to the AS, and require them to guard that against reuse (which is really tedious during development) or make them use it in a B.2 fashion. Instead, though, I could commission them with an AS response that gives them access to the AS. They'd do the N1/N2 dance of ACE rather than starting B2 (which is a bit better because they'll need that with any other server later on anyway), have static key material with the AS, but the would not be a CWT but a plain identifier (semantic or random). The audience of that token is the AS itself, which already knows the token so there's really no need to include actual information in there.

I see it's late in the spec process, so this may just be let slide. To ensure I stick to the letter of the specification, I'll use the hostname of the client and ROT-13 it ;-)

**Comment by chrysn** [comment]
From latest chat, it may say "**Self-contained** access tokens MUST be encrypted since". (The framework says that self-contained tokens must be encrypted or integrity-protected, and the latter is not an option for ACE-OSCORE)

**Comment by chrysn** [comment]
The very point of this has become moot as due to "The same parameters MUST be included as part of the access token.", all tokens must be self-contained (and thus encryption is required).

The point then becomes a "but there is a case for non-selfcontained tokens" (eg. when the RS is the AS and thus introspection is trivial), although that may not be a strong use case. Another use case are RSs that for complexity reason prefer introspection over self-contained tokens, but I'm not sure of the use case's strength either.

**Comment by fpalombini** [comment]
I see it as 2 points: first point is that we are adding a requirement on top of the framework about self contained tokens being encrypted. The framework (sections  5.8.1.1 and 6.1) states that:

> Self-contained tokens MUST, at a minimum,
>    be integrity protected but they MAY also be encrypted.

And

> If the access token contains the
>    symmetric key, this symmetric key MUST be encrypted by the
>    authorization server so that only the resource server can decrypt it.

I am tempted to say these requirements are enough for the OSCORE profile as well, and they don't need to be repeated. So my proposal would be to just remove the parts that say that tokens MUST be encrypted.

The second point is: do we want to allow for non-self contained tokens, given @chrysn use case?

**Comment by fpalombini** [comment]
Ok after discussion with @jimsch, @chrysn and @marco-tiloca-sics, the result of the discussion was that we can remove the requirement about the token being encrypted, as that is inherited from the framework. It is implicit that the token containing oscore security context is self-contained and hence must be integrity protected and may be encrypted, or that the symmetric ket must be encrypted (follows from the framework); on the other hand the token may not be self contained if introspection is done, and that would cover @chrysn's case.

I will send a mail to the wg to notify of this discussion.

**Comment by kaduk** [comment]
> The same parameters MUST be included as part of the access token

My recollection is that we had language very similar to this in the framework, and were interpreting it as allowing for the parameters to be retrieved either from a self-contained token or via an introspection technique.  Hopefully someone will jump in and correct me if I am mistaken.

**Comment by LudwigSeitz** [comment]
Yes, the phrasing would be better if it said something along the lines of "the same parameters MUST be included in the claims associated with the token", since the token may be opaque and only interpretable via introspection. 

/Ludwig 

Sent from my smartphone

---- kaduk wrote ----
